server:
  port: 9000

cache:
  provider: REDIS
  host: localhost
  port: 6379

springdoc:
  api-docs:
    title: My Custom API Documentation
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dcProjects
    username: root
    password: avinash.jh
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

    profiles:
      active: local

